#!/bin/bash
MAINCLASS=com.revature.App
CLASSPATH=

clean() {
        echo $'\nCleaning project...\n'
        rm -rf target/
}

verify() {
        if [ ! -d target/dependencies ]; then
                mkdir -p target/dependencies
        fi
        echo $'\nVerifying dependencies...\n'
        wget --show-progress -qcNP target/dependencies -i dependencies.txt
}

compile() {
        verify
        if [ ! -d target/classes ]; then
                mkdir -p target/classes
        fi
        
        echo $'\nCompiling...\n'
        javac \
                -cp "${CLASSPATH}"                      \
                -d target/classes/                      \
                -source 1.8                             \
                -target 1.8                             \
                -Xlint                                  \
                -sourcepath src/main/java/              \
                src/main/java/com/revature/App.java
}

compileTests() {
        compile
        if [ ! -d target/test-classes ]; then
                mkdir -p target/test-classes
        fi
        
        echo $'\nCompiling unit tests...\n'
        javac \
                -cp target/classes/:"${CLASSPATH}"                         \
                -d target/test-classes/                         \
                -source 1.8                                     \
                -target 1.8                                     \
                -Xlint                                          \
                -sourcepath src/test/java/:src/main/java/       \
                src/test/java/com/revature/AppTests.java
}

test() {
        compileTests

        echo $'\Running unit tests...\n'
        java \
                -cp target/classes/:target/test-classes/:"${CLASSPATH}" \
                org.junit.runner.JUnitCore \
                com.revature.AppTests

}

package() {
        test
        echo $'\nCreating Manifest...\n'
        echo "Main-Class:" $MAINCLASS > target/classes/Manifest.txt
        echo "Class-Path:" $(cd target && ls -1 dependencies/*) >> target/classes/Manifest.txt

        echo $'\nPackaging jar file...\n'
        jar cfm target/app.jar target/classes/Manifest.txt -C target/classes .
}

debug() {
        echo $'\nRunning in debug mode...\n'
        
        java \
        -cp target/classes/:"${CLASSPATH}" \
        -Dorg.slf4j.simpleLogger.defaultLogLevel=DEBUG \
        "${MAINCLASS}"
}

runjar() {
        echo $'\nRunning jar...\n'
        java -jar target/app.jar
}

for i in `ls target/dependencies/*` 
do
        CLASSPATH=${CLASSPATH}:${i}
done

for i in "$@"
do
        "$i"
done
